Optimize user submission flow
ACED-IDP/gen3_util pull request #26
Opened 2023-12-07 19:14 UTC by bwalsh

This PR has several enhancements:
* `auth`:  the user will only need to maintain a single credential ~/.gen3/gen3_client_config.ini per gen3-client instructions
  * a '--profile' option now exists on all commands
* `metadata generation`:  the system will default to filtering uploaded files to those files in the current manifest (that have been successfully uploaded)
* `metadata submission`:  the system will now automatically generate and submit metadata, additionally the system will default to immediately returning the job identifier.   The user can override this behavior and choose a) not to generate and submit or b) choose to wait for the job to complete

2023-12-18 16:52 UTC, matthewpeterkort commented
Had to go digging to figure out that the gen3_util by default looks for the first profile in the ~/.gen3/gen3_client_config.ini if you don't specify a profile using the flag. This should be somewhere in the docs or the very least in the README of this repo for developers wondering why their the authentication pytests are failing. 

1 test still fails:
```pytest tests/integration/test_project.py::test_project_bad_ping```
seems to rely on an option that may not exist anymore.

2023-12-18 18:36 UTC, matthewpeterkort requested changes

2023-12-18 18:36 UTC, matthewpeterkort commented on requirements.txt
> +fhir.resources==7.0.2
fhir.resources requirement on line 12 needs to be deleted because duplicate entry. Same for pyJwt library on line 14.

2023-12-18 18:36 UTC, matthewpeterkort commented on gen3_util/access/__init__.py
> +            url = url + "?" + "&".join(parms)
Guessing these "parms" additions are for harnessing the full functionality of the requestor API endpoint?

2023-12-18 18:36 UTC, matthewpeterkort commented on gen3_util/config/__init__.py
> +    return pathlib.Path(pathlib.Path.home() / ".gen3" / "gen3_client_config.ini")
This functionality should be a bit better documented, especially for people who have expired gen3_client configs in their gen3_client_config.ini file

2023-12-18 18:36 UTC, matthewpeterkort commented on gen3_util/files/remover.py
> +def rm(config: Config, object_id: str) -> dict:
Is there a test for this function?

2023-12-18 18:36 UTC, matthewpeterkort commented on gen3_util/meta/skeleton.py
> +    from gen3_util.files.manifest import ls as manifest_ls  # TODO fix circular import
How to fix this?

2023-12-19 19:25 UTC, bwalsh commented on requirements.txt
> +fhir.resources==7.0.2
done

2023-12-19 19:31 UTC, bwalsh commented on gen3_util/access/__init__.py
> +            url = url + "?" + "&".join(parms)
done

2023-12-19 19:36 UTC, bwalsh commented on gen3_util/config/__init__.py
> +    return pathlib.Path(pathlib.Path.home() / ".gen3" / "gen3_client_config.ini")
done

2023-12-19 20:24 UTC, bwalsh commented on gen3_util/files/remover.py
> +def rm(config: Config, object_id: str) -> dict:
added

2023-12-19 23:35 UTC, bwalsh commented on gen3_util/meta/skeleton.py
> +    from gen3_util.files.manifest import ls as manifest_ls  # TODO fix circular import
fixed

2023-12-20 19:10 UTC, merged