Add initial support for etags in manifest
ACED-IDP/gen3_util pull request #69
Opened 2024-03-29 18:12 UTC by lbeckman314

Work in progress — starts to resolve #68 by adding initial support for using the `etag` hash of an S3 object to upload to indexd.

2024-03-29 20:01 UTC, bwalsh requested changes
code in commit looks good. it would be nice to update docs & tests

2024-03-29 20:01 UTC, bwalsh commented on gen3_util/files/manifest.py
> +            hash = md5sum(file)
perfecto

2024-03-29 20:03 UTC, bwalsh commented
Some places md5 is mentioned in docs.

https://github.com/ACED-IDP/gen3_util/blob/0198c88ce3b6f0583037b0af9bb716c9c1f75b16/docs/git-lite-workflow.md?plain=1#L77

2024-03-29 20:04 UTC, bwalsh commented
Other places it is mentioned in code:

https://github.com/ACED-IDP/gen3_util/blob/0198c88ce3b6f0583037b0af9bb716c9c1f75b16/gen3_util/meta/skeleton.py#L35-L39

2024-03-29 20:04 UTC, bwalsh commented
To be complete we should refactor `ls` starting here

https://github.com/ACED-IDP/gen3_util/blob/0198c88ce3b6f0583037b0af9bb716c9c1f75b16/gen3_util/files/cli.py#L47-L48

2024-03-29 20:06 UTC, bwalsh commented
this is a simple unit test that could be changed to support etag
https://github.com/ACED-IDP/gen3_util/blob/0198c88ce3b6f0583037b0af9bb716c9c1f75b16/tests/unit/test_manifest.py#L14

2024-03-29 20:09 UTC, bwalsh commented
thanks.  this is a good start.
do tests pass now?

2024-05-02 01:10 UTC, lbeckman314 commented
# Limitations

Tried adding 'etag' without success, will need to look at the FHIR schema and see if other hashes are allowed in the extension?

https://github.com/ACED-IDP/gen3_util/blob/f348e79a6739440774c4e6a8763c822147a03934/gen3_util/meta/skeleton.py#L45-L49

# Testing

Running both unit and integration tests together (`pytest tests`) results in 7 failed unit tests. However running the tests separately (`pytest tests/unit && pytest tests/integration`) results in them passing.

Will need to investigate to see if there are some side effects from the integration tests that may be affecting the unit tests.

## Running Together ❌

```sh
➜ pytest tests

FAILED tests/unit/tabular/test_dir_to_tabular.py::test_dir_to_tabular - AssertionError: tests/fixtures/tabular does not exist
FAILED tests/unit/test_coding_conventions.py::test_coding_conventions - AssertionError: ['FAILURE: Python formatting and style for directory gen3_util/', 'FAILURE: Python f
ormatting and style for directory tests/']
FAILED tests/unit/test_config.py::test_custom_config - FileNotFoundError: [Errno 2] No such file or directory: 'tests/fixtures/custom_config/config.yaml'
FAILED tests/unit/test_files.py::test_uploader_validate_parameters - AssertionError: tests is not a directory
FAILED tests/unit/test_validate_directory.py::test_validate_directory_files - AssertionError: Expected 8 resources {'summary': {}}
FAILED tests/unit/test_validate_directory.py::test_validate_directory_zips - AssertionError: Expected 8 resources {'summary': {}}
FAILED tests/unit/test_validate_directory.py::test_validate_invalid_files - AssertionError: Expected exceptions []
========== 7 failed, 51 passed, 4 skipped in 361.63s (0:06:01) ==========
```

## Running Separately ✅

```sh
➜  pytest tests/unit && pytest tests/integration

========== test session starts ==========
platform darwin -- Python 3.12.3, pytest-8.2.0, pluggy-1.5.0
rootdir: /Users/beckmanl/code/gen3_util
configfile: pytest.ini
plugins: cov-5.0.0, anyio-4.3.0
collected 43 items

tests/unit/tabular/test_config.py ...                                                                                                                                [  6%]
tests/unit/tabular/test_default_columns.py ......                                                                                                                    [ 20%]
tests/unit/tabular/test_dir_to_tabular.py .                                                                                                                          [ 23%]
tests/unit/tabular/test_from_tabular.py ..                                                                                                                           [ 27%]
tests/unit/tabular/test_to_tabular.py .....                                                                                                                          [ 39%]
tests/unit/tabular/test_validate.py ...                                                                                                                              [ 46%]
tests/unit/test_cli.py .......                                                                                                                                       [ 62%]
tests/unit/test_coding.py ss                                                                                                                                         [ 67%]
tests/unit/test_coding_conventions.py .                                                                                                                              [ 69%]
tests/unit/test_config.py ..                                                                                                                                         [ 74%]
tests/unit/test_files.py ...                                                                                                                                         [ 81%]
tests/unit/test_job_dependencies.py ..                                                                                                                               [ 86%]
tests/unit/test_manifest.py .                                                                                                                                        [ 88%]
tests/unit/test_validate_directory.py ....                                                                                                                           [ 97%]
tests/unit/test_version.py .                                                                                                                                         [100%]

========== 41 passed, 2 skipped in 2.75s ==========
========== test session starts ==========
platform darwin -- Python 3.12.3, pytest-8.2.0, pluggy-1.5.0
rootdir: /Users/beckmanl/code/gen3_util
configfile: pytest.ini
plugins: cov-5.0.0, anyio-4.3.0
collected 19 items

tests/integration/test_access.py ..                                                                                                                                  [ 10%]
tests/integration/test_buckets.py .                                                                                                                                  [ 15%]
tests/integration/test_commit.py ...                                                                                                                                 [ 31%]
tests/integration/test_config.py .                                                                                                                                   [ 36%]
tests/integration/test_foreign_bucket.py .                                                                                                                           [ 42%]
tests/integration/test_init.py .                                                                                                                                     [ 47%]
tests/integration/test_meta.py s                                                                                                                                     [ 52%]
tests/integration/test_meta_skeleton.py .....                                                                                                                        [ 78%]
tests/integration/test_no_bucket.py s                                                                                                                                [ 84%]
tests/integration/test_project.py ...                                                                                                                                [100%]

========== 17 passed, 2 skipped in 295.45s (0:04:55) ==========
```

2024-10-08 17:10 UTC, lbeckman314 commented
Closing as complete! ✅ 

> External files can be indexed in Gen3 by using the ETag hash of the file:
> 
> [Add remote files to the manifest](https://aced-idp.github.io/workflows/upload/#add-remote-files-to-the-manifest)
> 
> ```sh
> g3t add s3://<Bucket>/<File> \
>   --etag <ETag> \
>   --size <Size> \
>   --modified <Date> \
>   --no-git-add
> ```

2024-10-08 17:10 UTC, closed without merging